import Foundation
import SwiftData

final class SampleData {
    static func preloadIfNeeded(modelContext: ModelContext) {
        let descriptor = FetchDescriptor<Exercise>()
        guard (try? modelContext.fetch(descriptor))?.isEmpty ?? true else { return }
        insertSampleExercises(modelContext: modelContext)
        insertSamplePreferences(modelContext: modelContext)
    }

    private static func insertSampleExercises(modelContext: ModelContext) {
        let exercises: [Exercise] = [
            // MARK: - Peito (18)
            Exercise(name: "Supino Reto", muscleGroup: "Peito", exerciseDescription: "Deitado no banco reto, empurre a barra para cima a partir do peito.", equipment: "Barra + Banco Reto", musclesWorked: "Peitoral maior, deltoide anterior, tríceps", imageName: "figure.strengthtraining.traditional"),
            Exercise(name: "Supino Inclinado", muscleGroup: "Peito", exerciseDescription: "Foco na porção superior do peitoral em banco inclinado a 45°.", equipment: "Barra + Banco Inclinado", musclesWorked: "Peitoral maior (clavicular), deltoide anterior", imageName: "figure.strengthtraining.traditional"),
            Exercise(name: "Supino Declinado", muscleGroup: "Peito", exerciseDescription: "Foco na porção inferior do peitoral em banco declinado.", equipment: "Barra + Banco Declinado", musclesWorked: "Peitoral maior (porção inferior)", imageName: "figure.strengthtraining.traditional"),
            Exercise(name: "Supino com Halteres Reto", muscleGroup: "Peito", exerciseDescription: "Maior amplitude de movimento que a barra.", equipment: "Halteres + Banco Reto", musclesWorked: "Peitoral maior, estabilizadores", imageName: "figure.strengthtraining.traditional"),
            Exercise(name: "Supino com Halteres Inclinado", muscleGroup: "Peito", exerciseDescription: "Halteres no banco inclinado para maior alongamento.", equipment: "Halteres + Banco Inclinado", musclesWorked: "Peitoral maior (clavicular), deltoide anterior", imageName: "figure.strengthtraining.traditional"),
            Exercise(name: "Crucifixo Reto", muscleGroup: "Peito", exerciseDescription: "Abra os braços com halteres em movimento de abraço.", equipment: "Halteres + Banco Reto", musclesWorked: "Peitoral maior (alongamento e contração)", imageName: "figure.strengthtraining.traditional"),
            Exercise(name: "Crucifixo Inclinado", muscleGroup: "Peito", exerciseDescription: "Crucifixo no banco inclinado para parte superior.", equipment: "Halteres + Banco Inclinado", musclesWorked: "Peitoral maior (clavicular)", imageName: "figure.strengthtraining.traditional"),
            Exercise(name: "Crossover na Polia", muscleGroup: "Peito", exerciseDescription: "Na polia alta, cruze as mãos à frente do corpo.", equipment: "Polia Dupla Alta", musclesWorked: "Peitoral maior, deltoide anterior", imageName: "figure.strengthtraining.traditional"),
            Exercise(name: "Peck Deck", muscleGroup: "Peito", exerciseDescription: "Sente na máquina e junte os braços à frente.", equipment: "Máquina Peck Deck", musclesWorked: "Peitoral maior", imageName: "figure.strengthtraining.traditional"),
            Exercise(name: "Pullover", muscleGroup: "Peito", exerciseDescription: "Deitado, passe o haltere por trás da cabeça.", equipment: "Haltere + Banco Reto", musclesWorked: "Peitoral maior, grande dorsal, serrátil", imageName: "figure.strengthtraining.traditional"),
            Exercise(name: "Flexão de Braços", muscleGroup: "Peito", exerciseDescription: "Flexão clássica no solo com mãos na largura dos ombros.", equipment: "Peso Corporal", musclesWorked: "Peitoral maior, deltoide anterior, tríceps", imageName: "figure.strengthtraining.traditional"),
            Exercise(name: "Flexão Declinada", muscleGroup: "Peito", exerciseDescription: "Pés elevados para maior ênfase no peitoral superior.", equipment: "Peso Corporal + Banco", musclesWorked: "Peitoral maior (clavicular), deltoide anterior", imageName: "figure.strengthtraining.traditional"),
            Exercise(name: "Flexão Diamante", muscleGroup: "Peito", exerciseDescription: "Mãos juntas em formato de diamante, foco no tríceps e peitoral interno.", equipment: "Peso Corporal", musclesWorked: "Tríceps, peitoral maior (interno)", imageName: "figure.strengthtraining.traditional"),
            Exercise(name: "Chest Press Máquina", muscleGroup: "Peito", exerciseDescription: "Empurre as alavancas da máquina sentado.", equipment: "Máquina Chest Press", musclesWorked: "Peitoral maior, deltoide anterior, tríceps", imageName: "figure.strengthtraining.traditional"),
            Exercise(name: "Supino com Pegada Fechada", muscleGroup: "Peito", exerciseDescription: "Mãos juntas na barra, foco no tríceps e peitoral interno.", equipment: "Barra + Banco Reto", musclesWorked: "Tríceps, peitoral maior (interno)", imageName: "figure.strengthtraining.traditional"),
            Exercise(name: "Flexão Explosiva", muscleGroup: "Peito", exerciseDescription: "Flexão com impulso para soltar as mãos do chão.", equipment: "Peso Corporal", musclesWorked: "Peitoral maior, deltoide, tríceps (potência)", imageName: "figure.strengthtraining.traditional"),
            Exercise(name: "Voador", muscleGroup: "Peito", exerciseDescription: "Máquina que simula crucifixo sentado.", equipment: "Máquina Voador", musclesWorked: "Peitoral maior", imageName: "figure.strengthtraining.traditional"),
            Exercise(name: "Flexão com Apoio", muscleGroup: "Peito", exerciseDescription: "Flexão com as mãos em anilhas ou suportes para maior amplitude.", equipment: "Anilhas ou Suportes", musclesWorked: "Peitoral maior, deltoide anterior, tríceps", imageName: "figure.strengthtraining.traditional"),

            // MARK: - Costas (25)
            Exercise(name: "Puxada Alta Frente", muscleGroup: "Costas", exerciseDescription: "Puxe a barra até a frente do peito, cotovelos para baixo.", equipment: "Polia Alta + Barra Longa", musclesWorked: "Latíssimo do dorso, romboides, trapézio, bíceps", imageName: "figure.rower"),
            Exercise(name: "Puxada Alta Atrás", muscleGroup: "Costas", exerciseDescription: "Puxe a barra atrás da nuca, cuidado com os ombros.", equipment: "Polia Alta + Barra Longa", musclesWorked: "Latíssimo do dorso, trapézio, romboides", imageName: "figure.rower"),
            Exercise(name: "Puxada com Triângulo", muscleGroup: "Costas", exerciseDescription: "Puxe o triângulo ao peito com pegada neutra.", equipment: "Polia Alta + Triângulo", musclesWorked: "Latíssimo do dorso (porção inferior), romboides", imageName: "figure.rower"),
            Exercise(name: "Remada Curvada", muscleGroup: "Costas", exerciseDescription: "Com barra, puxe até a barriga mantendo costas retas.", equipment: "Barra", musclesWorked: "Latíssimo do dorso, romboides, trapézio, deltoide posterior", imageName: "figure.rower"),
            Exercise(name: "Remada Unilateral", muscleGroup: "Costas", exerciseDescription: "Apoie joelho e mão no banco, puxe o haltere ao quadril.", equipment: "Halter + Banco", musclesWorked: "Latíssimo do dorso, romboides, bíceps", imageName: "figure.rower"),
            Exercise(name: "Remada Baixa", muscleGroup: "Costas", exerciseDescription: "Na polia baixa, puxe o triângulo ao abdômen.", equipment: "Polia Baixa + Triângulo", musclesWorked: "Latíssimo do dorso, romboides, trapézio médio", imageName: "figure.rower"),
            Exercise(name: "Remada Cavalinho", muscleGroup: "Costas", exerciseDescription: "Máquina com apoio de peito, puxe as alças ao corpo.", equipment: "Máquina Remada Cavalinho", musclesWorked: "Latíssimo do dorso, romboides, trapézio", imageName: "figure.rower"),
            Exercise(name: "Barra Fixa Pronada", muscleGroup: "Costas", exerciseDescription: "Puxe o corpo até a barra com palmas viradas para frente.", equipment: "Barra Fixa", musclesWorked: "Latíssimo do dorso, bíceps, romboides, trapézio", imageName: "figure.rower"),
            Exercise(name: "Barra Fixa Supinada", muscleGroup: "Costas", exerciseDescription: "Palmas viradas para você, maior ênfase no bíceps.", equipment: "Barra Fixa", musclesWorked: "Latíssimo do dorso, bíceps (maior ativação)", imageName: "figure.rower"),
            Exercise(name: "Barra Fixa Neutra", muscleGroup: "Costas", exerciseDescription: "Palmas viradas uma para a outra, pegada mais forte.", equipment: "Barra Fixa + Triângulo", musclesWorked: "Latíssimo do dorso, braquial, romboides", imageName: "figure.rower"),
            Exercise(name: "Levantamento Terra", muscleGroup: "Costas", exerciseDescription: "Levante a barra do chão até a posição em pé, costas retas.", equipment: "Barra + Anilhas", musclesWorked: "Cadeia posterior, erectores espinhais, glúteos, posteriores", imageName: "figure.rower"),
            Exercise(name: "Levantamento Terra Romeno", muscleGroup: "Costas", exerciseDescription: "Com pernas semi-estendidas, desça a barra até meio da canela.", equipment: "Barra", musclesWorked: "Posteriores da coxa, glúteos, erectores espinhais", imageName: "figure.rower"),
            Exercise(name: "Hiperextensão", muscleGroup: "Costas", exerciseDescription: "No banco romano, desça o tronco e suba contraindo lombar e glúteos.", equipment: "Banco Romano", musclesWorked: "Erectores espinhais, glúteos, posteriores", imageName: "figure.rower"),
            Exercise(name: "Encolhimento com Barra", muscleGroup: "Costas", exerciseDescription: "Eleve os ombros em direção às orelhas com barra nas mãos.", equipment: "Barra", musclesWorked: "Trapézio superior, elevador da escápula", imageName: "figure.rower"),
            Exercise(name: "Encolhimento com Halteres", muscleGroup: "Costas", exerciseDescription: "Mesmo movimento, mas com halteres ao lado do corpo.", equipment: "Halteres", musclesWorked: "Trapézio superior, elevador da escápula", imageName: "figure.rower"),
            Exercise(name: "Face Pull", muscleGroup: "Costas", exerciseDescription: "Puxe a polia alta ao rosto com cotovelos altos.", equipment: "Polia Alta + Corda", musclesWorked: "Deltoide posterior, trapézio médio, romboides", imageName: "figure.rower"),
            Exercise(name: "Remada na Máquina Smith", muscleGroup: "Costas", exerciseDescription: "Remada curvada usando a barra guiada da Smith.", equipment: "Smith Machine", musclesWorked: "Latíssimo do dorso, romboides, trapézio", imageName: "figure.rower"),
            Exercise(name: "Puxada na Máquina", muscleGroup: "Costas", exerciseDescription: "Máquina de puxada com pesos empilhados.", equipment: "Máquina de Puxada", musclesWorked: "Latíssimo do dorso, romboides, bíceps", imageName: "figure.rower"),
            Exercise(name: "Superman", muscleGroup: "Costas", exerciseDescription: "Deitado de bruços, levante braços e pernas simultaneamente.", equipment: "Peso Corporal", musclesWorked: "Erectores espinhais, glúteos, trapézio", imageName: "figure.rower"),
            Exercise(name: "Remada Invertida", muscleGroup: "Costas", exerciseDescription: "Deite sob a barra fixa e puxe o peito até ela.", equipment: "Barra Fixa Baixa", musclesWorked: "Romboides, trapézio médio, deltoide posterior", imageName: "figure.rower"),
            Exercise(name: "Pull Up", muscleGroup: "Costas", exerciseDescription: "Barra fixa com pegada pronada, puxe até o queixo passar.", equipment: "Barra Fixa", musclesWorked: "Latíssimo do dorso, bíceps, romboides, trapézio", imageName: "figure.rower"),
            Exercise(name: "Chin Up", muscleGroup: "Costas", exerciseDescription: "Barra fixa com pegada supinada, maior foco no bíceps.", equipment: "Barra Fixa", musclesWorked: "Latíssimo do dorso, bíceps braquial", imageName: "figure.rower"),
            Exercise(name: "Remada com Triângulo na Polia Baixa", muscleGroup: "Costas", exerciseDescription: "Puxe o triângulo ao abdômen mantendo costas retas.", equipment: "Polia Baixa + Triângulo", musclesWorked: "Latíssimo do dorso, romboides, bíceps", imageName: "figure.rower"),
            Exercise(name: "Puxada Aberta", muscleGroup: "Costas", exerciseDescription: "Puxada com barra longa e mãos afastadas.", equipment: "Polia Alta + Barra Longa", musclesWorked: "Latíssimo do dorso (largura)", imageName: "figure.rower"),
            Exercise(name: "Remada Serra", muscleGroup: "Costas", exerciseDescription: "Remada unilateral com apoio, puxe o haltere atrás do corpo.", equipment: "Halter + Banco", musclesWorked: "Latíssimo do dorso, romboides", imageName: "figure.rower"),

            // MARK: - Ombros (18)
            Exercise(name: "Desenvolvimento com Barra", muscleGroup: "Ombros", exerciseDescription: "Empurre a barra acima da cabeça a partir dos ombros.", equipment: "Barra", musclesWorked: "Deltoides (anterior, medial), tríceps", imageName: "figure.boxing"),
            Exercise(name: "Desenvolvimento com Halteres", muscleGroup: "Ombros", exerciseDescription: "Sente no banco e empurre os halteres acima da cabeça.", equipment: "Halteres + Banco", musclesWorked: "Deltoides, tríceps", imageName: "figure.boxing"),
            Exercise(name: "Desenvolvimento Arnold", muscleGroup: "Ombros", exerciseDescription: "Gire as palmas enquanto sobe os halteres, como Arnold fazia.", equipment: "Halteres", musclesWorked: "Deltoides (porções anterior, medial, posterior)", imageName: "figure.boxing"),
            Exercise(name: "Elevação Lateral", muscleGroup: "Ombros", exerciseDescription: "Com halteres, levante os braços lateralmente até a altura dos ombros.", equipment: "Halteres", musclesWorked: "Deltoide medial (lateral)", imageName: "figure.boxing"),
            Exercise(name: "Elevação Frontal", muscleGroup: "Ombros", exerciseDescription: "Levante os halteres à frente até a altura dos ombros.", equipment: "Halteres", musclesWorked: "Deltoide anterior", imageName: "figure.boxing"),
            Exercise(name: "Elevação Lateral Curvada", muscleGroup: "Ombros", exerciseDescription: "Curvado, levante os halteres lateralmente como se fosse voar.", equipment: "Halteres", musclesWorked: "Deltoide posterior", imageName: "figure.boxing"),
            Exercise(name: "Crucifixo Inverso", muscleGroup: "Ombros", exerciseDescription: "Na máquina, abra os braços para trás contra a resistência.", equipment: "Máquina Crucifixo Inverso", musclesWorked: "Deltoide posterior, romboides, trapézio", imageName: "figure.boxing"),
            Exercise(name: "Desenvolvimento Militar", muscleGroup: "Ombros", exerciseDescription: "Desenvolvimento com barra em pé, sem impulso das pernas.", equipment: "Barra", musclesWorked: "Deltoides, tríceps, core", imageName: "figure.boxing"),
            Exercise(name: "Desenvolvimento Máquina", muscleGroup: "Ombros", exerciseDescription: "Empurre as alavancas da máquina sentado.", equipment: "Máquina Shoulder Press", musclesWorked: "Deltoides, tríceps", imageName: "figure.boxing"),
            Exercise(name: "Remada Alta", muscleGroup: "Ombros", exerciseDescription: "Puxe a barra ao queixo com cotovelos para cima.", equipment: "Barra", musclesWorked: "Deltoides, trapézio superior", imageName: "figure.boxing"),
            Exercise(name: "Elevação Lateral na Polia", muscleGroup: "Ombros", exerciseDescription: "Na polia baixa, eleve o braço lateralmente.", equipment: "Polia Baixa", musclesWorked: "Deltoide medial", imageName: "figure.boxing"),
            Exercise(name: "Elevação Frontal na Polia", muscleGroup: "Ombros", exerciseDescription: "Na polia baixa, eleve o braço à frente.", equipment: "Polia Baixa", musclesWorked: "Deltoide anterior", imageName: "figure.boxing"),
            Exercise(name: "Rotação Externa", muscleGroup: "Ombros", exerciseDescription: "Com haltere ou polia, gire o braço para fora mantendo cotovelo colado.", equipment: "Haltere ou Polia", musclesWorked: "Manguito rotador (infraespinal, redondo menor)", imageName: "figure.boxing"),
            Exercise(name: "Rotação Interna", muscleGroup: "Ombros", exerciseDescription: "Gire o braço para dentro contra resistência.", equipment: "Polia ou Elástico", musclesWorked: "Manguito rotador (subescapular)", imageName: "figure.boxing"),
            Exercise(name: "Elevação Lateral com Cabo", muscleGroup: "Ombros", exerciseDescription: "Na polia cruzada, elevação lateral com tensão constante.", equipment: "Polia Cruzada", musclesWorked: "Deltoide medial", imageName: "figure.boxing"),
            Exercise(name: "Desenvolvimento Smith", muscleGroup: "Ombros", exerciseDescription: "Desenvolvimento na máquina Smith com barra guiada.", equipment: "Smith Machine", musclesWorked: "Deltoides, tríceps", imageName: "figure.boxing"),
            Exercise(name: "Pá de Ferro", muscleGroup: "Ombros", exerciseDescription: "Com halteres, gire as palmas para baixo e levante lateralmente.", equipment: "Halteres", musclesWorked: "Deltoide medial e posterior", imageName: "figure.boxing"),
            Exercise(name: "Upright Row com Halteres", muscleGroup: "Ombros", exerciseDescription: "Puxe os halteres ao queixo, cotovelos acima das mãos.", equipment: "Halteres", musclesWorked: "Deltoides, trapézio", imageName: "figure.boxing"),

            // MARK: - Bíceps (18)
            Exercise(name: "Rosca Direta", muscleGroup: "Bíceps", exerciseDescription: "Com barra, flexione os cotovelos levando a barra aos ombros.", equipment: "Barra Reta", musclesWorked: "Bíceps braquial", imageName: "figure.curling"),
            Exercise(name: "Rosca Alternada", muscleGroup: "Bíceps", exerciseDescription: "Alternando os braços, flexione o haltere ao ombro.", equipment: "Halteres", musclesWorked: "Bíceps braquial", imageName: "figure.curling"),
            Exercise(name: "Rosca Martelo", muscleGroup: "Bíceps", exerciseDescription: "Palmas viradas uma para a outra, flexione os halteres.", equipment: "Halteres", musclesWorked: "Braquial, braquiorradial", imageName: "figure.curling"),
            Exercise(name: "Rosca Scott", muscleGroup: "Bíceps", exerciseDescription: "Apoie os braços no banco Scott e flexione a barra W.", equipment: "Banco Scott + Barra W", musclesWorked: "Bíceps braquial (isolamento total)", imageName: "figure.curling"),
            Exercise(name: "Rosca Concentrada", muscleGroup: "Bíceps", exerciseDescription: "Sentado, apoie o cotovelo na coxa e flexione o haltere.", equipment: "Haltere", musclesWorked: "Bíceps braquial (pico)", imageName: "figure.curling"),
            Exercise(name: "Rosca na Polia Baixa", muscleGroup: "Bíceps", exerciseDescription: "Na polia baixa com barra reta, flexione os cotovelos.", equipment: "Polia Baixa + Barra", musclesWorked: "Bíceps braquial", imageName: "figure.curling"),
            Exercise(name: "Rosca no Cabo", muscleGroup: "Bíceps", exerciseDescription: "Rosca bilateral com cabos na polia baixa.", equipment: "Polia Baixa + Corda", musclesWorked: "Bíceps braquial", imageName: "figure.curling"),
            Exercise(name: "Rosca Inversa", muscleGroup: "Bíceps", exerciseDescription: "Com barra, palmas viradas para baixo, flexione os cotovelos.", equipment: "Barra", musclesWorked: "Braquiorradial, braquial", imageName: "figure.curling"),
            Exercise(name: "Rosca 21", muscleGroup: "Bíceps", exerciseDescription: "7 repetições parciais inferiores, 7 superiores e 7 completas.", equipment: "Barra", musclesWorked: "Bíceps braquial, braquiorradial", imageName: "figure.curling"),
            Exercise(name: "Rosca no Banco Inclinado", muscleGroup: "Bíceps", exerciseDescription: "Deitado no banco inclinado, flexione os halteres dos ombros.", equipment: "Halteres + Banco Inclinado", musclesWorked: "Bíceps braquial (alongamento máximo)", imageName: "figure.curling"),
            Exercise(name: "Rosca Martelo Cruzada", muscleGroup: "Bíceps", exerciseDescription: "Rosca martelo cruzando o corpo.", equipment: "Halteres", musclesWorked: "Braquial, braquiorradial", imageName: "figure.curling"),
            Exercise(name: "Rosca Punho", muscleGroup: "Bíceps", exerciseDescription: "Com antebraços apoiados, flexione o punho para cima.", equipment: "Barra ou Halteres", musclesWorked: "Flexores do punho, antebraço", imageName: "figure.curling"),
            Exercise(name: "Rosca no Banco Scott com Halteres", muscleGroup: "Bíceps", exerciseDescription: "Rosca unilateral no banco Scott com haltere.", equipment: "Banco Scott + Haltere", musclesWorked: "Bíceps braquial", imageName: "figure.curling"),
            Exercise(name: "Rosca na Máquina", muscleGroup: "Bíceps", exerciseDescription: "Máquina de rosca direta sentado.", equipment: "Máquina Rosca Direta", musclesWorked: "Bíceps braquial", imageName: "figure.curling"),
            Exercise(name: "Preacher Curl", muscleGroup: "Bíceps", exerciseDescription: "Rosca Scott com barra W.", equipment: "Banco Scott + Barra W", musclesWorked: "Bíceps braquial", imageName: "figure.curling"),
            Exercise(name: "Cable Curl", muscleGroup: "Bíceps", exerciseDescription: "Rosca na polia baixa com barra reta, tensão constante.", equipment: "Polia Baixa + Barra Reta", musclesWorked: "Bíceps braquial", imageName: "figure.curling"),
            Exercise(name: "Spider Curl", muscleGroup: "Bíceps", exerciseDescription: "Deitado de bruços no banco inclinado, flexione os halteres.", equipment: "Halteres + Banco Inclinado", musclesWorked: "Bíceps braquial", imageName: "figure.curling"),
            Exercise(name: "Zottman Curl", muscleGroup: "Bíceps", exerciseDescription: "Rosca com palmas para cima na subida e para baixo na descida.", equipment: "Halteres", musclesWorked: "Bíceps braquial, braquiorradial", imageName: "figure.curling"),

            // MARK: - Tríceps (18)
            Exercise(name: "Tríceps Corda", muscleGroup: "Tríceps", exerciseDescription: "Na polia alta com corda, puxe para baixo estendendo os cotovelos.", equipment: "Polia Alta + Corda", musclesWorked: "Tríceps braquial (porção lateral)", imageName: "figure.core.training"),
            Exercise(name: "Tríceps Francês", muscleGroup: "Tríceps", exerciseDescription: "Deitado, estenda a barra W de trás da cabeça.", equipment: "Barra W + Banco Reto", musclesWorked: "Tríceps braquial (porção longa)", imageName: "figure.core.training"),
            Exercise(name: "Tríceps Testa", muscleGroup: "Tríceps", exerciseDescription: "Deitado, desça a barra até a testa e estenda.", equipment: "Barra W ou Halteres + Banco", musclesWorked: "Tríceps braquial", imageName: "figure.core.training"),
            Exercise(name: "Tríceps Coice", muscleGroup: "Tríceps", exerciseDescription: "Curvado, estenda o haltere para trás mantendo o braço parado.", equipment: "Haltere", musclesWorked: "Tríceps braquial (porção lateral)", imageName: "figure.core.training"),
            Exercise(name: "Mergulho nas Paralelas", muscleGroup: "Tríceps", exerciseDescription: "Entre as paralelas, desça e suba com o peso do corpo.", equipment: "Barras Paralelas", musclesWorked: "Tríceps braquial, peitoral inferior", imageName: "figure.core.training"),
            Exercise(name: "Tríceps na Polia Alta", muscleGroup: "Tríceps", exerciseDescription: "Com barra reta na polia, empurre para baixo.", equipment: "Polia Alta + Barra Reta", musclesWorked: "Tríceps braquial", imageName: "figure.core.training"),
            Exercise(name: "Tríceps no Banco", muscleGroup: "Tríceps", exerciseDescription: "Mãos no banco atrás do corpo, desça e suba com o quadril.", equipment: "Banco", musclesWorked: "Tríceps braquial, peitoral", imageName: "figure.core.training"),
            Exercise(name: "Tríceps Máquina", muscleGroup: "Tríceps", exerciseDescription: "Na máquina de tríceps, empurre as alavancas.", equipment: "Máquina Tríceps", musclesWorked: "Tríceps braquial", imageName: "figure.core.training"),
            Exercise(name: "Tríceps Unilateral na Polia", muscleGroup: "Tríceps", exerciseDescription: "Com uma mão na polia, estende o braço para baixo.", equipment: "Polia Alta + Pegador", musclesWorked: "Tríceps braquial", imageName: "figure.core.training"),
            Exercise(name: "Tríceps Pulley", muscleGroup: "Tríceps", exerciseDescription: "Na polia alta usando corda, extensão completa.", equipment: "Polia Alta + Corda", musclesWorked: "Tríceps braquial", imageName: "figure.core.training"),
            Exercise(name: "Overhead Triceps Extension", muscleGroup: "Tríceps", exerciseDescription: "Em pé ou sentado, estenda o haltere acima da cabeça.", equipment: "Haltere", musclesWorked: "Tríceps braquial (porção longa)", imageName: "figure.core.training"),
            Exercise(name: "Skull Crusher", muscleGroup: "Tríceps", exerciseDescription: "Deitado, desça a barra W até a testa.", equipment: "Barra W + Banco Reto", musclesWorked: "Tríceps braquial", imageName: "figure.core.training"),
            Exercise(name: "Tríceps Martelo", muscleGroup: "Tríceps", exerciseDescription: "Com haltere, extensão atrás da cabeça com pegada neutra.", equipment: "Haltere", musclesWorked: "Tríceps braquial", imageName: "figure.core.training"),
            Exercise(name: "Tríceps Testa com Corda", muscleGroup: "Tríceps", exerciseDescription: "Deitado, use a corda para extensão sobre a cabeça.", equipment: "Banco + Corda", musclesWorked: "Tríceps braquial", imageName: "figure.core.training"),
            Exercise(name: "Kickback", muscleGroup: "Tríceps", exerciseDescription: "Curvado, estenda o haltere para trás contraindo o tríceps.", equipment: "Halteres", musclesWorked: "Tríceps braquial", imageName: "figure.core.training"),
            Exercise(name: "Tríceps Inclinado", muscleGroup: "Tríceps", exerciseDescription: "No banco inclinado, extensão de halteres atrás da cabeça.", equipment: "Halteres + Banco Inclinado", musclesWorked: "Tríceps braquial (porção longa)", imageName: "figure.core.training"),
            Exercise(name: "Close Grip Bench", muscleGroup: "Tríceps", exerciseDescription: "Supino reto com mãos juntas, foco no tríceps.", equipment: "Barra + Banco Reto", musclesWorked: "Tríceps braquial, peitoral interno", imageName: "figure.core.training"),
            Exercise(name: "Tríceps Polia Alta Corda", muscleGroup: "Tríceps", exerciseDescription: "Na polia, puxe a corda para baixo abrindo no final.", equipment: "Polia Alta + Corda", musclesWorked: "Tríceps braquial (porção lateral)", imageName: "figure.core.training"),

            // MARK: - Pernas (30)
            Exercise(name: "Agachamento Livre", muscleGroup: "Pernas", exerciseDescription: "Com barra nas costas, agache até 90° e volte.", equipment: "Barra + Power Rack", musclesWorked: "Quadríceps, glúteos, posteriores, core", imageName: "figure.walk"),
            Exercise(name: "Agachamento Frontal", muscleGroup: "Pernas", exerciseDescription: "Barra apoiada na frente dos ombros, tronco mais ereto.", equipment: "Barra", musclesWorked: "Quadríceps (maior ênfase), glúteos", imageName: "figure.walk"),
            Exercise(name: "Agachamento Sumô", muscleGroup: "Pernas", exerciseDescription: "Pés bem abertos, barra entre as pernas ou haltere.", equipment: "Barra ou Halteres", musclesWorked: "Glúteos, adutores, quadríceps", imageName: "figure.walk"),
            Exercise(name: "Agachamento Búlgaro", muscleGroup: "Pernas", exerciseDescription: "Um pé no chão, outro no banco, agache com a perna da frente.", equipment: "Halteres + Banco", musclesWorked: "Quadríceps, glúteos, estabilizadores", imageName: "figure.walk"),
            Exercise(name: "Agachamento Goblet", muscleGroup: "Pernas", exerciseDescription: "Segure um haltere ou kettlebell junto ao peito e agache.", equipment: "Haltere ou Kettlebell", musclesWorked: "Quadríceps, glúteos, core", imageName: "figure.walk"),
            Exercise(name: "Leg Press 45°", muscleGroup: "Pernas", exerciseDescription: "Na máquina, empurre a plataforma com os pés.", equipment: "Máquina Leg Press 45°", musclesWorked: "Quadríceps, glúteos, posteriores", imageName: "figure.walk"),
            Exercise(name: "Leg Press Horizontal", muscleGroup: "Pernas", exerciseDescription: "Máquina de leg press na horizontal.", equipment: "Máquina Leg Press", musclesWorked: "Quadríceps, glúteos", imageName: "figure.walk"),
            Exercise(name: "Cadeira Extensora", muscleGroup: "Pernas", exerciseDescription: "Sentado, estenda as pernas contra a resistência.", equipment: "Máquina Cadeira Extensora", musclesWorked: "Quadríceps", imageName: "figure.walk"),
            Exercise(name: "Mesa Flexora", muscleGroup: "Pernas", exerciseDescription: "Deitado na máquina, flexione as pernas levando o rolo aos glúteos.", equipment: "Máquina Mesa Flexora", musclesWorked: "Posteriores da coxa (isquiotibiais)", imageName: "figure.walk"),
            Exercise(name: "Cadeira Flexora", muscleGroup: "Pernas", exerciseDescription: "Sentado na máquina, flexione as pernas para baixo.", equipment: "Máquina Cadeira Flexora", musclesWorked: "Posteriores da coxa", imageName: "figure.walk"),
            Exercise(name: "Stiff", muscleGroup: "Pernas", exerciseDescription: "Com pernas estendidas, desça a barra mantendo costas retas.", equipment: "Barra", musclesWorked: "Posteriores da coxa, glúteos, lombar", imageName: "figure.walk"),
            Exercise(name: "Afundo com Barra", muscleGroup: "Pernas", exerciseDescription: "Com barra nas costas, dê passos largos à frente alternando as pernas.", equipment: "Barra", musclesWorked: "Quadríceps, glúteos, estabilizadores", imageName: "figure.walk"),
            Exercise(name: "Afundo com Halteres", muscleGroup: "Pernas", exerciseDescription: "Mesmo movimento com halteres nas mãos.", equipment: "Halteres", musclesWorked: "Quadríceps, glúteos", imageName: "figure.walk"),
            Exercise(name: "Elevação Pélvica", muscleGroup: "Pernas", exerciseDescription: "Deitado, eleve o quadril com barra apoiada.", equipment: "Barra + Banco", musclesWorked: "Glúteos, posteriores", imageName: "figure.walk"),
            Exercise(name: "Glúteo 4 Apoios", muscleGroup: "Pernas", exerciseDescription: "De quatro, eleve uma perna flexionada para cima.", equipment: "Peso Corporal", musclesWorked: "Glúteos", imageName: "figure.walk"),
            Exercise(name: "Panturrilha em Pé", muscleGroup: "Pernas", exerciseDescription: "Em pé na máquina, eleve os calcanhares.", equipment: "Máquina Panturrilha em Pé", musclesWorked: "Gastrocnêmio, sóleo", imageName: "figure.walk"),
            Exercise(name: "Panturrilha Sentado", muscleGroup: "Pernas", exerciseDescription: "Sentado na máquina, eleve os calcanhares.", equipment: "Máquina Panturrilha Sentado", musclesWorked: "Sóleo", imageName: "figure.walk"),
            Exercise(name: "Panturrilha no Leg Press", muscleGroup: "Pernas", exerciseDescription: "No leg press, estenda os pés na ponta da plataforma.", equipment: "Leg Press", musclesWorked: "Gastrocnêmio, sóleo", imageName: "figure.walk"),
            Exercise(name: "Cadeira Abdutora", muscleGroup: "Pernas", exerciseDescription: "Sentado, abra as pernas contra a resistência.", equipment: "Máquina Abdutora", musclesWorked: "Glúteo médio, glúteo mínimo", imageName: "figure.walk"),
            Exercise(name: "Cadeira Adutora", muscleGroup: "Pernas", exerciseDescription: "Sentado, feche as pernas contra a resistência.", equipment: "Máquina Adutora", musclesWorked: "Adutores (pectíneo, grácil, adutor longo)", imageName: "figure.walk"),
            Exercise(name: "Agachamento no Smith", muscleGroup: "Pernas", exerciseDescription: "Agachamento guiado na máquina Smith.", equipment: "Smith Machine", musclesWorked: "Quadríceps, glúteos", imageName: "figure.walk"),
            Exercise(name: "Hack Squat", muscleGroup: "Pernas", exerciseDescription: "Na máquina Hack, costas apoiadas, agache flexionando os joelhos.", equipment: "Máquina Hack Squat", musclesWorked: "Quadríceps, glúteos", imageName: "figure.walk"),
            Exercise(name: "Passada", muscleGroup: "Pernas", exerciseDescription: "Com halteres, dê passos longos alternando as pernas.", equipment: "Halteres", musclesWorked: "Quadríceps, glúteos", imageName: "figure.walk"),
            Exercise(name: "Step Up", muscleGroup: "Pernas", exerciseDescription: "Suba em um banco com halteres, alternando as pernas.", equipment: "Banco + Halteres", musclesWorked: "Quadríceps, glúteos", imageName: "figure.walk"),
            Exercise(name: "Sissy Squat", muscleGroup: "Pernas", exerciseDescription: "Agachamento inclinando o tronco para trás, foco no quadríceps.", equipment: "Peso Corporal ou Halteres", musclesWorked: "Quadríceps", imageName: "figure.walk"),
            Exercise(name: "Glute Bridge", muscleGroup: "Pernas", exerciseDescription: "Deitado, eleve o quadril contraindo os glúteos.", equipment: "Peso Corporal", musclesWorked: "Glúteos, core", imageName: "figure.walk"),
            Exercise(name: "Hip Thrust", muscleGroup: "Pernas", exerciseDescription: "Com barra no quadril, eleve o tronco apoiado no banco.", equipment: "Barra + Banco", musclesWorked: "Glúteos, posteriores", imageName: "figure.walk"),
            Exercise(name: "Agachamento com Salto", muscleGroup: "Pernas", exerciseDescription: "Agache e salte explosivamente.", equipment: "Peso Corporal", musclesWorked: "Quadríceps, glúteos, panturrilhas (potência)", imageName: "figure.walk"),
            Exercise(name: "Afundo Reverso", muscleGroup: "Pernas", exerciseDescription: "Dê o passo para trás em vez de para frente.", equipment: "Halteres", musclesWorked: "Quadríceps, glúteos", imageName: "figure.walk"),
            Exercise(name: "Stiff Unilateral", muscleGroup: "Pernas", exerciseDescription: "Com haltere, stiff em uma perna só.", equipment: "Haltere", musclesWorked: "Posteriores, glúteos, equilíbrio", imageName: "figure.walk"),

            // MARK: - Abdômen (20)
            Exercise(name: "Abdominal Crunch", muscleGroup: "Abdômen", exerciseDescription: "Deitado, flexione o tronco elevando os ombros do chão.", equipment: "Peso Corporal", musclesWorked: "Reto abdominal", imageName: "figure.core.training"),
            Exercise(name: "Abdominal Infra", muscleGroup: "Abdômen", exerciseDescription: "Deitado, eleve as pernas flexionadas levando os joelhos ao peito.", equipment: "Peso Corporal", musclesWorked: "Reto abdominal (porção inferior)", imageName: "figure.core.training"),
            Exercise(name: "Abdominal Oblíquo", muscleGroup: "Abdômen", exerciseDescription: "Toque o calcanhar oposto com o cotovelo alternando os lados.", equipment: "Peso Corporal", musclesWorked: "Oblíquos externos, internos", imageName: "figure.core.training"),
            Exercise(name: "Prancha", muscleGroup: "Abdômen", exerciseDescription: "Mantenha o corpo reto apoiado nos antebraços e pontas dos pés.", equipment: "Peso Corporal", musclesWorked: "Core, reto abdominal, oblíquos, lombar", imageName: "figure.core.training"),
            Exercise(name: "Prancha Lateral", muscleGroup: "Abdômen", exerciseDescription: "Apoiado em um antebraço, mantenha o corpo alinhado de lado.", equipment: "Peso Corporal", musclesWorked: "Oblíquos, glúteo médio", imageName: "figure.core.training"),
            Exercise(name: "Elevação de Pernas Suspenso", muscleGroup: "Abdômen", exerciseDescription: "Suspenso na barra fixa, eleve as pernas retas.", equipment: "Barra Fixa", musclesWorked: "Reto abdominal (inferior), flexores do quadril", imageName: "figure.core.training"),
            Exercise(name: "Bicicleta no Ar", muscleGroup: "Abdômen", exerciseDescription: "Deitado, pedale no ar tocando o cotovelo no joelho oposto.", equipment: "Peso Corporal", musclesWorked: "Reto abdominal, oblíquos", imageName: "figure.core.training"),
            Exercise(name: "Russian Twist", muscleGroup: "Abdômen", exerciseDescription: "Sentado, gire o tronco de um lado para o outro com halter.", equipment: "Halter ou Peso Corporal", musclesWorked: "Oblíquos, reto abdominal", imageName: "figure.core.training"),
            Exercise(name: "Abdominal na Máquina", muscleGroup: "Abdômen", exerciseDescription: "Sentado na máquina, flexione o tronco para frente.", equipment: "Máquina Abdominal", musclesWorked: "Reto abdominal", imageName: "figure.core.training"),
            Exercise(name: "Abdominal na Polia Alta", muscleGroup: "Abdômen", exerciseDescription: "Ajoelhado na polia alta, flexione o tronco puxando a corda.", equipment: "Polia Alta + Corda", musclesWorked: "Reto abdominal", imageName: "figure.core.training"),
            Exercise(name: "Abdominal Canivete", muscleGroup: "Abdômen", exerciseDescription: "Deitado, eleve braços e pernas simultaneamente se encontrando.", equipment: "Peso Corporal", musclesWorked: "Reto abdominal (superior e inferior)", imageName: "figure.core.training"),
            Exercise(name: "Abdominal V-up", muscleGroup: "Abdômen", exerciseDescription: "Deitado, eleve o tronco e as pernas estendidas formando um V.", equipment: "Peso Corporal", musclesWorked: "Reto abdominal, flexores do quadril", imageName: "figure.core.training"),
            Exercise(name: "Prancha com Toque", muscleGroup: "Abdômen", exerciseDescription: "Na prancha, toque o ombro oposto alternando as mãos.", equipment: "Peso Corporal", musclesWorked: "Core, oblíquos, estabilizadores", imageName: "figure.core.training"),
            Exercise(name: "Leg Raise", muscleGroup: "Abdômen", exerciseDescription: "Deitado, eleve as pernas estendidas a 90°.", equipment: "Peso Corporal", musclesWorked: "Reto abdominal (inferior)", imageName: "figure.core.training"),
            Exercise(name: "Crunch na Polia", muscleGroup: "Abdômen", exerciseDescription: "Com a polia alta, puxe a corda flexionando o tronco.", equipment: "Polia Alta + Corda", musclesWorked: "Reto abdominal", imageName: "figure.core.training"),
            Exercise(name: "Abdominal Infra Suspenso", muscleGroup: "Abdômen", exerciseDescription: "Suspenso na barra, eleve os joelhos ao peito.", equipment: "Barra Fixa", musclesWorked: "Reto abdominal (inferior)", imageName: "figure.core.training"),
            Exercise(name: "Prancha com Movimento", muscleGroup: "Abdômen", exerciseDescription: "Na prancha, mova os pés para os lados alternadamente.", equipment: "Peso Corporal", musclesWorked: "Core, oblíquos, estabilizadores", imageName: "figure.core.training"),
            Exercise(name: "Abdominal Remador", muscleGroup: "Abdômen", exerciseDescription: "Sentado com pernas estendidas, gire o tronco tocando o chão.", equipment: "Peso Corporal", musclesWorked: "Oblíquos, reto abdominal", imageName: "figure.core.training"),
            Exercise(name: "Hollow Body Hold", muscleGroup: "Abdômen", exerciseDescription: "Deitado, mantenha braços e pernas estendidos elevados do chão.", equipment: "Peso Corporal", musclesWorked: "Core, reto abdominal, flexores do quadril", imageName: "figure.core.training"),
            Exercise(name: "Abdominal com Halter", muscleGroup: "Abdômen", exerciseDescription: "Crunch com halter junto ao peito para maior resistência.", equipment: "Halter", musclesWorked: "Reto abdominal", imageName: "figure.core.training"),

            // MARK: - Cardio (20)
            Exercise(name: "Corrida na Esteira", muscleGroup: "Cardio", exerciseDescription: "Corra na esteira em ritmo moderado a intenso.", equipment: "Esteira", musclesWorked: "Sistema cardiovascular, pernas, glúteos", imageName: "heart.fill"),
            Exercise(name: "Bicicleta Ergométrica", muscleGroup: "Cardio", exerciseDescription: "Pedale na bicicleta ergométrica em ritmo constante.", equipment: "Bicicleta Ergométrica", musclesWorked: "Sistema cardiovascular, quadríceps, glúteos", imageName: "heart.fill"),
            Exercise(name: "Transport", muscleGroup: "Cardio", exerciseDescription: "Máquina de escada simulando subida de degraus.", equipment: "Transport", musclesWorked: "Sistema cardiovascular, glúteos, panturrilhas", imageName: "heart.fill"),
            Exercise(name: "Elíptico", muscleGroup: "Cardio", exerciseDescription: "Movimento elíptico suave e contínuo.", equipment: "Aparelho Elíptico", musclesWorked: "Sistema cardiovascular, pernas, glúteos", imageName: "heart.fill"),
            Exercise(name: "Pular Corda", muscleGroup: "Cardio", exerciseDescription: "Pule a corda em ritmo moderado a rápido.", equipment: "Corda", musclesWorked: "Sistema cardiovascular, panturrilhas, ombros", imageName: "heart.fill"),
            Exercise(name: "Burpee", muscleGroup: "Cardio", exerciseDescription: "Agache, estenda as pernas para trás, faça flexão, volte e salte.", equipment: "Peso Corporal", musclesWorked: "Sistema cardiovascular, corpo inteiro", imageName: "heart.fill"),
            Exercise(name: "Mountain Climber", muscleGroup: "Cardio", exerciseDescription: "Na posição de flexão, traga os joelhos alternadamente ao peito.", equipment: "Peso Corporal", musclesWorked: "Sistema cardiovascular, core, ombros", imageName: "heart.fill"),
            Exercise(name: "Box Jump", muscleGroup: "Cardio", exerciseDescription: "Salte com os dois pés sobre uma caixa ou plataforma.", equipment: "Caixa Pliométrica", musclesWorked: "Sistema cardiovascular, quadríceps, glúteos, panturrilhas", imageName: "heart.fill"),
            Exercise(name: "Remo", muscleGroup: "Cardio", exerciseDescription: "Na máquina de remo, puxe o cabo simulando remada.", equipment: "Máquina de Remo", musclesWorked: "Sistema cardiovascular, costas, pernas, braços", imageName: "heart.fill"),
            Exercise(name: "Bicicleta Spinning", muscleGroup: "Cardio", exerciseDescription: "Bicicleta indoor com resistência ajustável.", equipment: "Bicicleta Spinning", musclesWorked: "Sistema cardiovascular, quadríceps, glúteos", imageName: "heart.fill"),
            Exercise(name: "Escada", muscleGroup: "Cardio", exerciseDescription: "Suba e desça degraus em ritmo acelerado.", equipment: "Escada ou Step", musclesWorked: "Sistema cardiovascular, glúteos, panturrilhas", imageName: "heart.fill"),
            Exercise(name: "Polichinelo", muscleGroup: "Cardio", exerciseDescription: "Salte abrindo braços e pernas simultaneamente.", equipment: "Peso Corporal", musclesWorked: "Sistema cardiovascular, ombros, pernas", imageName: "heart.fill"),
            Exercise(name: "Jumping Jack", muscleGroup: "Cardio", exerciseDescription: "Polichinelo clássico para aquecimento cardiovascular.", equipment: "Peso Corporal", musclesWorked: "Sistema cardiovascular, corpo inteiro", imageName: "heart.fill"),
            Exercise(name: "Battle Rope", muscleGroup: "Cardio", exerciseDescription: "Agite cordas grossas em ondas alternadas ou simultâneas.", equipment: "Corda Grossa (Battle Rope)", musclesWorked: "Sistema cardiovascular, ombros, braços, core", imageName: "heart.fill"),
            Exercise(name: "Kettlebell Swing", muscleGroup: "Cardio", exerciseDescription: "Com kettlebell entre as pernas, balance-o para frente com o quadril.", equipment: "Kettlebell", musclesWorked: "Sistema cardiovascular, glúteos, posteriores, core", imageName: "heart.fill"),
            Exercise(name: "HIIT Circuito", muscleGroup: "Cardio", exerciseDescription: "Alternância de exercícios de alta intensidade com descanso curto.", equipment: "Peso Corporal", musclesWorked: "Sistema cardiovascular, corpo inteiro", imageName: "heart.fill"),
            Exercise(name: "Sprint", muscleGroup: "Cardio", exerciseDescription: "Corra em velocidade máxima por curta distância.", equipment: "Tênis de corrida", musclesWorked: "Sistema cardiovascular, quadríceps, glúteos", imageName: "heart.fill"),
            Exercise(name: "Stair Master", muscleGroup: "Cardio", exerciseDescription: "Máquina de escada giratória contínua.", equipment: "Stair Master", musclesWorked: "Sistema cardiovascular, glúteos, panturrilhas", imageName: "heart.fill"),
            Exercise(name: "Corda Naval", muscleGroup: "Cardio", exerciseDescription: "Bata a corda grossa no chão alternando os braços.", equipment: "Corda Grossa", musclesWorked: "Sistema cardiovascular, ombros, braços, core", imageName: "heart.fill"),
            Exercise(name: "Corrida Estacionária", muscleGroup: "Cardio", exerciseDescription: "Corra sem sair do lugar elevando os joelhos.", equipment: "Peso Corporal", musclesWorked: "Sistema cardiovascular, pernas", imageName: "heart.fill"),
        ]

        for exercise in exercises {
            modelContext.insert(exercise)
        }
        try? modelContext.save()
    }

    private static func insertSamplePreferences(modelContext: ModelContext) {
        let prefs = NotificationPreference()
        modelContext.insert(prefs)
        try? modelContext.save()
    }
}
